"""empty message

Revision ID: 940cfe7e6e94
Revises: feff4823e5db
Create Date: 2020-02-26 10:52:57.100126

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '940cfe7e6e94'
down_revision = 'feff4823e5db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profiles', sa.Column('password', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_profiles', 'password')
    # ### end Alembic commands ###
